name = "CannotWaitForTheseOptimisers"
uuid = "16124dda-d9fe-413b-a880-e3f4df3aa341"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
